server:
  port: 9002

spring:
  application:
    name: sso-demo1


logging:
  level:
    org.springframework.security: DEBUG

oauth2:
  server: http://127.0.0.1:9001

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: sso-demo
      client-secret: sso-demo
      access-token-uri: ${oauth2.server}/oauth/token
      user-authorization-uri: ${oauth2.server}/oauth/authorize
    resource:
      jwt:
         key-uri: ${oauth2.server}/oauth/token_key
